#!/bin/sh
. "$(dirname "$0")/_/husky.sh"


[ -d "./dist/" ] && rm -rf ./dist/
npm run build
cd dist
git init
git status
giturl=$(git remote get-url origin)
git remote add gh-pages giturl
git checkout -b gh-pages
git add --all
git commit -m "build"
git push --set-upstream gh-pages gh-pages -f
cd ..
rm -r dist
